{{- if and .Values.mcpRelay.enabled .Values.mcpRelay.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "searxng.relay.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "searxng.relay.labels" . | nindent 4 }}
  {{- with (merge (dict) .Values.mcpRelay.serviceAccount.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.mcpRelay.serviceAccount.automountServiceAccountToken }}
{{- end }}
