#!/usr/bin/env bash
# Generate the chart's Secrets with real random credentials.
#
#   ./gen-secrets.sh <release> <namespace> [standalone|replication] > secrets.yaml
#   kubectl -n <namespace> apply -f secrets.yaml
#
# Prints to stdout so you can pipe it into sops/sealed-secrets instead of
# applying it directly. Nothing is written to disk and nothing is applied.
set -euo pipefail

RELEASE="${1:?usage: gen-secrets.sh <release> <namespace> [standalone|replication]}"
NAMESPACE="${2:?usage: gen-secrets.sh <release> <namespace> [standalone|replication]}"
ARCH="${3:-standalone}"

case "$ARCH" in
  standalone|replication) ;;
  *) echo "third argument must be 'standalone' or 'replication'" >&2; exit 1 ;;
esac

command -v openssl >/dev/null || { echo "openssl not found" >&2; exit 1; }

# Alphanumeric only: these end up inside a valkey:// URL, so anything that
# would need percent-encoding is avoided rather than escaped.
# `head -c` would SIGPIPE the producer, which `set -o pipefail` turns into a
# failure, so read a fixed amount and trim with cut instead.
rand_alnum() { openssl rand -base64 96 | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-"$1"; }

SECRET_KEY="$(openssl rand -hex 32)"
VALKEY_PASSWORD="$(rand_alnum 32)"
TOKEN_CLAUDE="$(openssl rand -hex 32)"
TOKEN_AGENT="$(openssl rand -hex 32)"
TOKEN_SCRAPE="$(openssl rand -hex 32)"

# Mirror the chart's fullname logic: Helm collapses the name when the release
# name already contains the chart name, so `helm install searxng ...` yields
# `searxng-valkey-primary`, not `searxng-searxng-valkey-primary`.
case "$RELEASE" in
  *searxng*) FULLNAME="$RELEASE" ;;
  *)         FULLNAME="${RELEASE}-searxng" ;;
esac
PRIMARY_HOST="${FULLNAME}-valkey-primary.${NAMESPACE}.svc"

cat <<YAML
# Generated by gen-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Release: ${RELEASE}   Namespace: ${NAMESPACE}   Valkey: ${ARCH}
# Replica target: ${PRIMARY_HOST}
#
# Treat this file as a credential. Do not commit it in the clear.
---
apiVersion: v1
kind: Secret
metadata:
  name: ${RELEASE}-searxng-secret
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: searxng
type: Opaque
stringData:
  secret-key: "${SECRET_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ${RELEASE}-searxng-valkey
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: searxng
type: Opaque
stringData:
  valkey-password: "${VALKEY_PASSWORD}"
  valkey.conf: |
    port 6379
    protected-mode yes
    requirepass ${VALKEY_PASSWORD}
    dir /data
    loglevel warning
    save ""
    appendonly no
    maxmemory-policy allkeys-lru
YAML

if [ "$ARCH" = "replication" ]; then
cat <<YAML
    repl-diskless-sync yes
    repl-diskless-sync-delay 5
  valkey-replica.conf: |
    port 6379
    protected-mode yes
    requirepass ${VALKEY_PASSWORD}
    masterauth ${VALKEY_PASSWORD}
    dir /data
    loglevel warning
    save ""
    appendonly no
    replicaof ${PRIMARY_HOST} 6379
    replica-read-only yes
    replica-serve-stale-data yes
    maxmemory-policy allkeys-lru
YAML
fi

cat <<YAML
---
apiVersion: v1
kind: Secret
metadata:
  name: ${RELEASE}-searxng-mcp-relay
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: searxng
type: Opaque
stringData:
  tokens: |
    claude-desktop:${TOKEN_CLAUDE}
    agent-ci:${TOKEN_AGENT}
    prometheus:${TOKEN_SCRAPE}
---
# Separate object so Prometheus's RBAC can be scoped here and not to the token
# file above. Same value as the prometheus line - the relay authenticates
# /metrics against that file, so the duplicate is unavoidable.
apiVersion: v1
kind: Secret
metadata:
  name: ${RELEASE}-searxng-mcp-relay-scrape
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/part-of: searxng
type: Opaque
stringData:
  scrape-token: "${TOKEN_SCRAPE}"
YAML

cat >&2 <<MSG

Wire these up with:

  searxng:
    existingSecret: ${RELEASE}-searxng-secret
  valkey:
    architecture: ${ARCH}
    auth:
      existingSecret: ${RELEASE}-searxng-valkey
  mcpRelay:
    auth:
      existingSecret: ${RELEASE}-searxng-mcp-relay
    metrics:
      existingSecret: ${RELEASE}-searxng-mcp-relay-scrape

Replicas will sync from: ${PRIMARY_HOST}
Verify after install with:
  kubectl -n ${NAMESPACE} exec ${FULLNAME}-valkey-primary-0 -c valkey -- valkey-cli info replication

Client tokens (give each client its own, revoke individually):
  claude-desktop  ${TOKEN_CLAUDE}
  agent-ci        ${TOKEN_AGENT}
MSG
